import {
  ADD_PLAYER,
  ADD_TEAM,
  ADD_COACH,
  TEAM_SEARCH,
  PLAYER_SEARCH,
  COACH_SEARCH,
  TEAM_TYPE_FILTER,
  PLAYER_POSITION_SEARCH,
  COACH_TEAM_SEARCH,
  EDIT_TEAM,
  EDIT_PLAYER,
  EDIT_COACH,
} from "./constants";

const initialState = {
  coachTeamSearch: "",
  playerPositionSearch: "",
  teamTypeFilter: "",
  teamSearchQuery: "",
  playerSearchQuery: "",
  coachSearchQuery: "",
  database: {
    teams: [
      {
        players: [
          "P-ky8hnntmpq6g1uyycri",
          "P-ky8hnntmhbcf9gcoihw",
          "P-ky8hnntm3ivff4ju3nm",
          "P-ky8hnntmjc2189araab",
          "P-ky8hnntmyecu7x0zez",
          "P-ky8hnntm00tehpshgypb",
          "P-ky8hnntms0is83t9pj",
          "P-ky8hnntmubgru86l5bf",
          "P-ky8hnntm9myb7t5nj6n",
          "P-ky8ece65hzmxnbiiq3a",
          "P-ky8hnntns3s30i2stu",
        ],
        name: "Bayern Munich",
        teamID: "T-ky8dawustkmu220jr8o",
        teamCountry: "Munich, Germany",
        teamStadium: "Allianz Arena",
        dateOfFoundation: "1990",
        teamType: { value: "Club Teams" },
        teamAttackNumber: 99,
        teamMIDFIELDNumber: 99,
        teamDEFENSENumber: 99,
        teamImg:
          "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1b/FC_Bayern_M%C3%BCnchen_logo_%282017%29.svg/270px-FC_Bayern_M%C3%BCnchen_logo_%282017%29.svg.png",
      },
      {
        players: [
          "P-ky8kmmse2hudvuu7lob",
          "P-ky8kmmsed6gn251tdom",
          "P-ky8kmmsectxwuo2dzgt",
          "P-ky8kmmsexos1qhi64gr",
          "P-ky8kmmse4d2hiybkvm2",
          "P-ky8kmmsej572wusbkxo",
          "P-ky8kmmselc9el8mp4hb",
          "P-ky8kmmseu7pgw1l13ci",
          "P-ky8kmmseq5ub42ppul",
          "P-ky8kmmsefssp1rqkala",
          "P-ky8kmmsepcmn43xpw0b",
        ],
        name: "Manchester United",
        teamID: "T-ky8dd3ex1k20os2uafb",
        teamCountry: "Manchester,England",
        teamStadium: "Old Trafford",
        dateOfFoundation: "1902",
        teamType: { value: "Club Teams" },
        teamAttackNumber: 99,
        teamMIDFIELDNumber: 99,
        teamDEFENSENumber: 99,
        teamImg:
          "https://upload.wikimedia.org/wikipedia/en/thumb/7/7a/Manchester_United_FC_crest.svg/270px-Manchester_United_FC_crest.svg.png",
      },
    ],
    players: [
      {
        name: "Sven Ulreich",
        playerID: "P-ky8hnntmpq6g1uyycri",
        playerPosition: "GoalKeeper",
        playerCurrentTeam: "Bayern Munich",
        dateOfBirth: "03/08/1988",
        playerOffensiveAwareness: 25,
        playerBallControl: 22,
        playerDribbling: 13,
        playerTightPossession: 75,
        playerLowPass: 60,
        playerLoftedPass: 86,
        playerFinishing: 13,
        playerHeading: 25,
        playerSetPieceTaking: 70,
        playerCurl: 14,
        playerSpeed: 60,
        playerAcceleration: 54,
        playerKickingPower: 68,
        playerJump: 77,
        playerPhysicalContact: 80,
        playerBalance: 35,
        playerStamina: 43,
        playerImg:
          "https://i.bundesliga.com/player/dfl-obj-0000lt-dfl-clu-00000g-dfl-sea-0001k5.png",
      },
      {
        name: "Benjamin Pavard",
        playerID: "P-ky8hnntmhbcf9gcoihw",
        playerPosition: "Defender",
        playerCurrentTeam: "Bayern Munich",
        dateOfBirth: "28/03/1996",
        playerOffensiveAwareness: 69,
        playerBallControl: 77,
        playerDribbling: 68,
        playerTightPossession: 76,
        playerLowPass: 75,
        playerLoftedPass: 76,
        playerFinishing: 43,
        playerHeading: 80,
        playerSetPieceTaking: 51,
        playerCurl: 63,
        playerSpeed: 69,
        playerAcceleration: 68,
        playerKickingPower: 71,
        playerJump: 86,
        playerPhysicalContact: 75,
        playerBalance: 66,
        playerStamina: 79,
        playerImg:
          "https://i.bundesliga.com/player/dfl-obj-0027g0-dfl-clu-00000g-dfl-sea-0001k5.png",
      },
      {
        name: "Niklas Süle",
        playerID: "P-ky8hnntm3ivff4ju3nm",
        playerPosition: "Defender",
        playerCurrentTeam: "Bayern Munich",
        dateOfBirth: "03/09/1995",
        playerOffensiveAwareness: 86,
        playerBallControl: 64,
        playerDribbling: 49,
        playerTightPossession: 76,
        playerLowPass: 80,
        playerLoftedPass: 70,
        playerFinishing: 22,
        playerHeading: 84,
        playerSetPieceTaking: 32,
        playerCurl: 28,
        playerSpeed: 79,
        playerAcceleration: 51,
        playerKickingPower: 78,
        playerJump: 42,
        playerPhysicalContact: 93,
        playerBalance: 33,
        playerStamina: 66,
        playerImg:
          "https://i.bundesliga.com/player/dfl-obj-0001ht-dfl-clu-00000g-dfl-sea-0001k5.png",
      },
      {
        name: "Joshua Kimmich",
        playerID: "P-ky8hnntmjc2189araab",
        playerPosition: "MidFielder",
        playerCurrentTeam: "Bayern Munich",
        dateOfBirth: "08/02/1995",
        playerOffensiveAwareness: 89,
        playerBallControl: 85,
        playerDribbling: 83,
        playerTightPossession: 85,
        playerLowPass: 87,
        playerLoftedPass: 90,
        playerFinishing: 68,
        playerHeading: 72,
        playerSetPieceTaking: 44,
        playerCurl: 85,
        playerSpeed: 65,
        playerAcceleration: 77,
        playerKickingPower: 78,
        playerJump: 79,
        playerPhysicalContact: 68,
        playerBalance: 84,
        playerStamina: 96,
        playerImg:
          "https://i.bundesliga.com/player/dfl-obj-0002f5-dfl-clu-00000g-dfl-sea-0001k5.png",
      },
      {
        name: "Marcel Sabitzer",
        playerID: "P-ky8hnntmyecu7x0zez",
        playerPosition: "MidFielder",
        playerCurrentTeam: "Bayern Munich",
        dateOfBirth: "17/03/1994",
        playerOffensiveAwareness: 78,
        playerBallControl: 82,
        playerDribbling: 79,
        playerTightPossession: 80,
        playerLowPass: 84,
        playerLoftedPass: 81,
        playerFinishing: 79,
        playerHeading: 60,
        playerSetPieceTaking: 72,
        playerCurl: 76,
        playerSpeed: 75,
        playerAcceleration: 75,
        playerKickingPower: 88,
        playerJump: 71,
        playerPhysicalContact: 76,
        playerBalance: 79,
        playerStamina: 58,
        playerImg:
          "https://i.bundesliga.com/player/dfl-obj-002666-dfl-clu-00000g-dfl-sea-0001k5.png",
      },
      {
        name: "Marc Roca",
        playerID: "P-ky8hnntm00tehpshgypb",
        playerPosition: "MidFielder",
        playerCurrentTeam: "Bayern Munich",
        dateOfBirth: "26/11/1996",
        playerOffensiveAwareness: 69,
        playerBallControl: 76,
        playerDribbling: 72,
        playerTightPossession: 74,
        playerLowPass: 81,
        playerLoftedPass: 85,
        playerFinishing: 59,
        playerHeading: 42,
        playerSetPieceTaking: 68,
        playerCurl: 66,
        playerSpeed: 50,
        playerAcceleration: 50,
        playerKickingPower: 66,
        playerJump: 57,
        playerPhysicalContact: 65,
        playerBalance: 65,
        playerStamina: 70,
        playerImg:
          "https://i.bundesliga.com/player/dfl-obj-002gm2-dfl-clu-00000g-dfl-sea-0001k5.png",
      },
      {
        name: "Jamal Musiala",
        playerID: "P-ky8hnntms0is83t9pj",
        playerPosition: "Forward",
        playerCurrentTeam: "Bayern Munich",
        dateOfBirth: "26/02/2003",
        playerOffensiveAwareness: 46,
        playerBallControl: 85,
        playerDribbling: 87,
        playerTightPossession: 78,
        playerLowPass: 76,
        playerLoftedPass: 67,
        playerFinishing: 76,
        playerHeading: 42,
        playerSetPieceTaking: 42,
        playerCurl: 63,
        playerSpeed: 73,
        playerAcceleration: 80,
        playerKickingPower: 70,
        playerJump: 47,
        playerPhysicalContact: 43,
        playerBalance: 90,
        playerStamina: 60,
        playerImg:
          "https://i.bundesliga.com/player/dfl-obj-002gcr-dfl-clu-00000g-dfl-sea-0001k5.png",
      },
      {
        name: "Serge Gnabry",
        playerID: "P-ky8hnntmubgru86l5bf",
        playerPosition: "Forward",
        playerCurrentTeam: "Bayern Munich",
        dateOfBirth: "14/07/1995",
        playerOffensiveAwareness: 63,
        playerBallControl: 83,
        playerDribbling: 88,
        playerTightPossession: 80,
        playerLowPass: 82,
        playerLoftedPass: 78,
        playerFinishing: 87,
        playerHeading: 42,
        playerSetPieceTaking: 68,
        playerCurl: 74,
        playerSpeed: 77,
        playerAcceleration: 90,
        playerKickingPower: 87,
        playerJump: 65,
        playerPhysicalContact: 69,
        playerBalance: 88,
        playerStamina: 78,
        playerImg:
          "https://i.bundesliga.com/player/dfl-obj-0027g6-dfl-clu-00000g-dfl-sea-0001k5.png",
      },
      {
        name: "Malik Tillman",
        playerID: "P-ky8hnntm9myb7t5nj6n",
        playerPosition: "Forward",
        playerCurrentTeam: "Bayern Munich",
        dateOfBirth: "28/05/2002",
        playerOffensiveAwareness: 43,
        playerBallControl: 64,
        playerDribbling: 62,
        playerTightPossession: 56,
        playerLowPass: 59,
        playerLoftedPass: 43,
        playerFinishing: 68,
        playerHeading: 61,
        playerSetPieceTaking: 58,
        playerCurl: 44,
        playerSpeed: 66,
        playerAcceleration: 68,
        playerKickingPower: 70,
        playerJump: 62,
        playerPhysicalContact: 58,
        playerBalance: 66,
        playerStamina: 58,
        playerImg:
          "https://i.bundesliga.com/player/dfl-obj-002gcu-dfl-clu-00000g-dfl-sea-0001k5.png",
      },
      {
        name: "Thomas Müller",
        playerID: "P-ky8ece65hzmxnbiiq3a",
        playerPosition: "Forward",
        playerCurrentTeam: "Bayern Munich",
        dateOfBirth: "13/09/1989",
        playerOffensiveAwareness: 90,
        playerBallControl: 81,
        playerDribbling: 75,
        playerTightPossession: 90,
        playerLowPass: 82,
        playerLoftedPass: 74,
        playerFinishing: 85,
        playerHeading: 81,
        playerSetPieceTaking: 60,
        playerCurl: 81,
        playerSpeed: 68,
        playerAcceleration: 68,
        playerKickingPower: 78,
        playerJump: 77,
        playerPhysicalContact: 67,
        playerBalance: 71,
        playerStamina: 86,
        playerImg:
          "https://i.bundesliga.com/player/dfl-obj-0000ia-dfl-clu-00000g-dfl-sea-0001k5.png",
      },
      {
        name: "Robert Lewandowski",
        playerID: "P-ky8hnntns3s30i2stu",
        playerPosition: "Forward",
        playerCurrentTeam: "Bayern Munich",
        dateOfBirth: "21/08/1988",
        playerOffensiveAwareness: 81,
        playerBallControl: 88,
        playerDribbling: 85,
        playerTightPossession: 88,
        playerLowPass: 85,
        playerLoftedPass: 70,
        playerFinishing: 95,
        playerHeading: 90,
        playerSetPieceTaking: 89,
        playerCurl: 79,
        playerSpeed: 79,
        playerAcceleration: 77,
        playerKickingPower: 90,
        playerJump: 85,
        playerPhysicalContact: 86,
        playerBalance: 82,
        playerStamina: 76,
        playerImg:
          "https://i.bundesliga.com/player/dfl-obj-00000m-dfl-clu-00000g-dfl-sea-0001k5.png",
      },
      {
        name: "David de Gea",
        playerID: "P-ky8kmmse2hudvuu7lob",
        playerPosition: "Goalkeeper",
        playerCurrentTeam: "Manchester United",
        dateOfBirth: "07/11/1990",
        playerOffensiveAwareness: 38,
        playerBallControl: 38,
        playerDribbling: 18,
        playerTightPossession: 63,
        playerLowPass: 50,
        playerLoftedPass: 43,
        playerFinishing: 13,
        playerHeading: 21,
        playerSetPieceTaking: 29,
        playerCurl: 21,
        playerSpeed: 58,
        playerAcceleration: 57,
        playerKickingPower: 57,
        playerJump: 67,
        playerPhysicalContact: 55,
        playerBalance: 43,
        playerStamina: 43,
        playerImg:
          "https://resources.premierleague.com/premierleague/photos/players/250x250/p51940.png",
      },
      {
        name: "Aaron Wan-Bissaka",
        playerID: "P-ky8kmmsed6gn251tdom",
        playerPosition: "Defender",
        playerCurrentTeam: "Manchester United",
        dateOfBirth: "26/11/1997",
        playerOffensiveAwareness: 77,
        playerBallControl: 74,
        playerDribbling: 78,
        playerTightPossession: 74,
        playerLowPass: 75,
        playerLoftedPass: 58,
        playerFinishing: 44,
        playerHeading: 51,
        playerSetPieceTaking: 44,
        playerCurl: 74,
        playerSpeed: 88,
        playerAcceleration: 82,
        playerKickingPower: 70,
        playerJump: 67,
        playerPhysicalContact: 72,
        playerBalance: 72,
        playerStamina: 81,
        playerImg:
          "https://resources.premierleague.com/premierleague/photos/players/250x250/p214590.png",
      },
      {
        name: "Phil Jones",
        playerID: "P-ky8kmmsectxwuo2dzgt",
        playerPosition: "Defender",
        playerCurrentTeam: "Manchester United",
        dateOfBirth: "21/02/1992",
        playerOffensiveAwareness: 86,
        playerBallControl: 54,
        playerDribbling: 57,
        playerTightPossession: 62,
        playerLowPass: 69,
        playerLoftedPass: 66,
        playerFinishing: 44,
        playerHeading: 77,
        playerSetPieceTaking: 50,
        playerCurl: 38,
        playerSpeed: 51,
        playerAcceleration: 50,
        playerKickingPower: 68,
        playerJump: 79,
        playerPhysicalContact: 76,
        playerBalance: 48,
        playerStamina: 31,
        playerImg:
          "https://resources.premierleague.com/premierleague/photos/players/250x250/p76359.png",
      },
      {
        name: "Raphaël Varane",
        playerID: "P-ky8kmmsexos1qhi64gr",
        playerPosition: "Defender",
        playerCurrentTeam: "Manchester United",
        dateOfBirth: "25/04/1993",
        playerOffensiveAwareness: 80,
        playerBallControl: 78,
        playerDribbling: 59,
        playerTightPossession: 83,
        playerLowPass: 78,
        playerLoftedPass: 76,
        playerFinishing: 46,
        playerHeading: 86,
        playerSetPieceTaking: 43,
        playerCurl: 46,
        playerSpeed: 85,
        playerAcceleration: 79,
        playerKickingPower: 52,
        playerJump: 81,
        playerPhysicalContact: 86,
        playerBalance: 39,
        playerStamina: 76,
        playerImg:
          "https://resources.premierleague.com/premierleague/photos/players/250x250/p90152.png",
      },
      {
        name: "Luke Shaw",
        playerID: "P-ky8kmmse4d2hiybkvm2",
        playerPosition: "Defender",
        playerCurrentTeam: "Manchester United",
        dateOfBirth: "12/07/1995",
        playerOffensiveAwareness: 84,
        playerBallControl: 80,
        playerDribbling: 80,
        playerTightPossession: 82,
        playerLowPass: 81,
        playerLoftedPass: 69,
        playerFinishing: 44,
        playerHeading: 78,
        playerSetPieceTaking: 44,
        playerCurl: 83,
        playerSpeed: 81,
        playerAcceleration: 77,
        playerKickingPower: 70,
        playerJump: 77,
        playerPhysicalContact: 80,
        playerBalance: 77,
        playerStamina: 79,
        playerImg:
          "https://resources.premierleague.com/premierleague/photos/players/250x250/p106760.png",
      },
      {
        name: "Scott McTominay",
        playerID: "P-ky8kmmsej572wusbkxo",
        playerPosition: "Midfielder",
        playerCurrentTeam: "Manchester United",
        dateOfBirth: "08/12/1996",
        playerOffensiveAwareness: 88,
        playerBallControl: 76,
        playerDribbling: 78,
        playerTightPossession: 76,
        playerLowPass: 79,
        playerLoftedPass: 80,
        playerFinishing: 71,
        playerHeading: 78,
        playerSetPieceTaking: 60,
        playerCurl: 72,
        playerSpeed: 69,
        playerAcceleration: 62,
        playerKickingPower: 85,
        playerJump: 73,
        playerPhysicalContact: 84,
        playerBalance: 60,
        playerStamina: 84,
        playerImg:
          "https://resources.premierleague.com/premierleague/photos/players/250x250/p195851.png",
      },
      {
        name: "Nemanja Matic",
        playerID: "P-ky8kmmselc9el8mp4hb",
        playerPosition: "Midfielder",
        playerCurrentTeam: "Manchester United",
        dateOfBirth: "01/08/1988",
        playerOffensiveAwareness: 76,
        playerBallControl: 79,
        playerDribbling: 75,
        playerTightPossession: 83,
        playerLowPass: 82,
        playerLoftedPass: 82,
        playerFinishing: 59,
        playerHeading: 72,
        playerSetPieceTaking: 64,
        playerCurl: 70,
        playerSpeed: 43,
        playerAcceleration: 33,
        playerKickingPower: 84,
        playerJump: 63,
        playerPhysicalContact: 82,
        playerBalance: 47,
        playerStamina: 54,
        playerImg:
          "https://resources.premierleague.com/premierleague/photos/players/250x250/p62398.png",
      },
      {
        name: "Mason Greenwood",
        playerID: "P-ky8kmmseu7pgw1l13ci",
        playerPosition: "Forward",
        playerCurrentTeam: "Manchester United",
        dateOfBirth: "01/10/2001",
        playerOffensiveAwareness: 59,
        playerBallControl: 77,
        playerDribbling: 81,
        playerTightPossession: 77,
        playerLowPass: 76,
        playerLoftedPass: 69,
        playerFinishing: 82,
        playerHeading: 65,
        playerSetPieceTaking: 67,
        playerCurl: 78,
        playerSpeed: 84,
        playerAcceleration: 83,
        playerKickingPower: 85,
        playerJump: 67,
        playerPhysicalContact: 67,
        playerBalance: 76,
        playerStamina: 74,
        playerImg:
          "https://resources.premierleague.com/premierleague/photos/players/250x250/p220688.png",
      },
      {
        name: "Jadon Sancho",
        playerID: "P-ky8kmmseq5ub42ppul",
        playerPosition: "Forward",
        playerCurrentTeam: "Manchester United",
        dateOfBirth: "25/03/2000",
        playerOffensiveAwareness: 44,
        playerBallControl: 90,
        playerDribbling: 92,
        playerTightPossession: 86,
        playerLowPass: 87,
        playerLoftedPass: 70,
        playerFinishing: 82,
        playerHeading: 38,
        playerSetPieceTaking: 62,
        playerCurl: 84,
        playerSpeed: 78,
        playerAcceleration: 85,
        playerKickingPower: 73,
        playerJump: 51,
        playerPhysicalContact: 68,
        playerBalance: 90,
        playerStamina: 74,
        playerImg:
          "https://resources.premierleague.com/premierleague/photos/players/250x250/p209243.png",
      },
      {
        name: "Edinson Cavani",
        playerID: "P-ky8kmmsefssp1rqkala",
        playerPosition: "Forward",
        playerCurrentTeam: "Manchester United",
        dateOfBirth: "14/02/1987",
        playerOffensiveAwareness: 81,
        playerBallControl: 81,
        playerDribbling: 74,
        playerTightPossession: 85,
        playerLowPass: 75,
        playerLoftedPass: 52,
        playerFinishing: 88,
        playerHeading: 88,
        playerSetPieceTaking: 85,
        playerCurl: 76,
        playerSpeed: 68,
        playerAcceleration: 64,
        playerKickingPower: 87,
        playerJump: 88,
        playerPhysicalContact: 76,
        playerBalance: 57,
        playerStamina: 79,
        playerImg:
          "https://resources.premierleague.com/premierleague/photos/players/250x250/p40720.png",
      },
      {
        name: "Cristiano Ronaldo",
        playerID: "P-ky8kmmsepcmn43xpw0b",
        playerPosition: "Forward",
        playerCurrentTeam: "Manchester United",
        dateOfBirth: "05/02/1985",
        playerOffensiveAwareness: 95,
        playerBallControl: 90,
        playerDribbling: 90,
        playerTightPossession: 95,
        playerLowPass: 80,
        playerLoftedPass: 77,
        playerFinishing: 95,
        playerHeading: 90,
        playerSetPieceTaking: 88,
        playerCurl: 81,
        playerSpeed: 88,
        playerAcceleration: 84,
        playerKickingPower: 94,
        playerJump: 95,
        playerPhysicalContact: 80,
        playerBalance: 80,
        playerStamina: 80,
        playerImg:
          "https://resources.premierleague.com/premierleague/photos/players/250x250/p14937.png",
      },
    ],

    coaches: [
      {
        name: "Julian Nagelsmann",
        coachID:
          "C-" + Date.now().toString(36) + Math.random().toString(36).substr(2),
        dateOfBirth: "23 July 1987",
        coachNationality: "German",
        coachCurrentTeam: "Bayern Munich",
        coachImg:
          "https://cdn.vox-cdn.com/thumbor/2LqTwd6tVo7rRlXDbk66EErkD8I=/1400x1400/filters:format(jpeg)/cdn.vox-cdn.com/uploads/chorus_asset/file/22740954/1189274686.jpg",
        coachExperience: 99,
        coachLeadershipSkills: 99,
        coachCoachingHistory: 99,
      },
    ],
  },
};

const Reducer = (state = initialState, action) => {
  switch (action.type) {
    case ADD_TEAM: {
      const obj = JSON.parse(JSON.stringify(state));

      obj.database.teams.push(action.payload);

      return obj;
    }
    case ADD_PLAYER: {
      const obj = JSON.parse(JSON.stringify(state));

      obj.database.players.push(action.payload);

      return obj;
    }
    case ADD_COACH: {
      const obj = JSON.parse(JSON.stringify(state));

      obj.database.coaches.push(action.payload);

      return obj;
    }
    case TEAM_SEARCH: {
      return {
        ...state,
        teamSearchQuery: action.payload,
      };
    }
    case PLAYER_SEARCH: {
      return {
        ...state,
        playerSearchQuery: action.payload,
      };
    }
    case COACH_SEARCH: {
      return {
        ...state,
        coachSearchQuery: action.payload,
      };
    }
    case TEAM_TYPE_FILTER: {
      return {
        ...state,
        teamTypeFilter: action.payload,
      };
    }
    case PLAYER_POSITION_SEARCH: {
      return {
        ...state,
        playerPositionSearch: action.payload,
      };
    }
    case COACH_TEAM_SEARCH: {
      return {
        ...state,
        coachTeamSearch: action.payload,
      };
    }
    case EDIT_TEAM: {
      return {
        ...state,
        database: {
          ...state.database,
          teams: state.database.teams.map((team) =>
            team.teamID === action.payload.teamID ? action.payload : team
          ),
        },
      };
    }
    case EDIT_PLAYER: {
      return {
        ...state,
        database: {
          ...state.database,
          players: state.database.players.map((player) =>
            player.playerID === action.payload.playerID
              ? action.payload
              : player
          ),
        },
      };
    }
    case EDIT_COACH: {
      return {
        ...state,
        database: {
          ...state.database,
          coaches: state.database.coaches.map((coach) =>
            coach.coachID === action.payload.coachID ? action.payload : coach
          ),
        },
      };
    }
    default:
      return state;
  }
};

export default Reducer;
